# Generated by Django 2.0.1 on 2018-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('yes_answer', models.BooleanField(verbose_name=False)),
                ('no_answer', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
